spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_URL}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        show-sql: true
        